### ISSUE TITLE
Invalid prop: type check failed for prop "options".

### ISSUE THREAD

**Issue by Symbolk** [FE-Mars/monaco-editor-vue#1]
When I tried the exmaple in README/Using with Webpack, the browser reports such an error:

Invalid prop: type check failed for prop "options". Expected Object, got String with value "{options}".

The options in the template and the data() are exactly same with the README. Any help?

**Comment by FE-Mars** [comment]
I am very sorry, I am wrong in the instance of README. I have committed a new version
