### ISSUE TITLE
how to use in nuxt

### ISSUE THREAD

**Issue by zouyn** [FE-Mars/monaco-editor-vue#11]
how to use in nuxt

**Comment by ManishKarki1997** [comment]
### In nuxt.config.js
```

import MonacoWebpackPlugin from 'monaco-editor/webpack'

// if the above doesn't work, install 'monaco-editor-webpack-plugin' and import it
import MonacoWebpackPlugin from 'monaco-editor-webpack-plugin'
```

then, 

inside nuxt.config.js, in build configuration,
do like this

```
build: {
    /*
    ** You can extend webpack config here
    */
    plugins: [
      new MonacoWebpackPlugin({
        languages: ['javascript', 'python', 'java']
      })
    ],
    extend(config, ctx) {
    }
  }

```

Now you can just import the editor in a component, put it in template and use it as shown in the readme

**Comment by sakibwebworm** [comment]
I am having this error while running in nuxt "Cannot find module 'monaco-editor/esm/vs/editor/editor.worker'"

**Comment by hawkofsky** [comment]
Hi, @ManishKarki1997, I added monaco-editor to nuxt as you indicated, but I faced the following error.

`TypeError: _this._model.onDidChangeRawContent is not a function`
`    at new Cursor (cursor.js?f961:154)`
`    at StandaloneEditor.CodeEditorWidget._attachModel (codeEditorWidget.js?4a22:963)`
`    at StandaloneEditor._attachModel (standaloneCodeEditor.js?e05c:204)`
`    at new StandaloneEditor (standaloneCodeEditor.js?e05c:186)`
`    at eval (standaloneEditor.js?3955:58)`
`    at withAllStandaloneServices (standaloneEditor.js?3955:45)`
`    at Object.create (standaloneEditor.js?3955:57)`
`    at VueComponent.initMonaco (index.js?b61c:124)`
`    at VueComponent.mounted (index.js?b61c:105)`
`    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)`

could you tell me why this happended?

**Comment by miketromba** [comment]
![image](https://user-images.githubusercontent.com/25141252/103465159-3b4ddb00-4d07-11eb-8798-98c26b5b81f7.png)

I'm also getting an error when trying this.

**Comment by agtraveso** [comment]
@miketromba I fixed it downgrading monaco-editor-webpack-plugin to 1.7.0 version.

related issue: https://github.com/microsoft/monaco-editor-webpack-plugin/issues/92
