### ISSUE TITLE
How to get the editor Instance from create() ?

### ISSUE THREAD

**Issue by dschiller** [FE-Mars/monaco-editor-vue#12]
`monaco.editor.create(..);` fails with `Uncaught TypeError: Cannot read property 'addEventListener' of null`

How to access the created Editor Instance ?

I also tried to use `editorMounted`. But that doesn't work. There is no reaction.

``<MonacoEditor width="100%" height="354" :options="options" @change="onChange" @editorMounted="onEditorMounted"></MonacoEditor>``

``editorMounted`` seems not to be executed.

I want to add an Action with 

```
editor.addAction({
	// An unique identifier of the contributed action.
	id: 'my-unique-id',

	// A label of the action that will be presented to the user.
	label: 'My Label!!!',

	// An optional array of keybindings for the action.
	keybindings: [
		monaco.KeyMod.CtrlCmd | monaco.KeyCode.F10,
		// chord
		monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_K, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_M)
	],

	// A precondition for this action.
	precondition: null,

	// A rule to evaluate on top of the precondition in order to dispatch the keybindings.
	keybindingContext: null,

	contextMenuGroupId: 'navigation',

	contextMenuOrder: 1.5,

	// Method that will be executed when the action is triggered.
	// @param editor The editor instance is passed in as a convinience
	run: function(ed) {
		alert("i'm running => " + ed.getPosition());
		return null;
	}
});
```

**Comment by FE-Mars** [comment]
@dschiller  **editorMounted** is not an event, just a property

**Comment by dschiller** [comment]
The Docu describe it as: `` editorMounted(editor, monaco) an event emitted when the editor has been mounted (similar to mounted of Vue). ``

How can I achieve the Possibility to add an Action with ``editor.addAction({...})`` ?

**Comment by FE-Mars** [comment]
@dschiller I will modify the doc
You just need to make the following changes
```
@editorMounted => :editorMounted
```
I'll close the current issue

**Comment by dschiller** [comment]
I tried your advice but I don't get it to work:

![image](https://user-images.githubusercontent.com/3144986/78338062-5af67e00-7592-11ea-9119-72e2c20c409d.png)

![image](https://user-images.githubusercontent.com/3144986/78338094-6e094e00-7592-11ea-9e85-bbd587a3a2e5.png)

Maybe you can show an Example.

Thank's a lot!

**Comment by FE-Mars** [comment]
@dschiller 
```jsx
<MonacoEditor width="100%" height="354" :options="options" @change="onChange" :editorMounted="onEditorMounted"></MonacoEditor>
```

**Comment by dschiller** [comment]
Crazy. Sure - a Property. Now I understand. Was confused by your ``=>`` Chars. Thank you!

**Comment by dschiller** [comment]
I changed it to the Property:

![image](https://user-images.githubusercontent.com/3144986/78874122-2ed47480-7a4c-11ea-86a1-d1b10355486a.png)

But it still doesn't get executed in the Method:

![image](https://user-images.githubusercontent.com/3144986/78874212-53305100-7a4c-11ea-99a0-55f389f4a934.png)

![image](https://user-images.githubusercontent.com/3144986/78874318-7ce97800-7a4c-11ea-9cbc-df2a8debee39.png)
