### ISSUE TITLE
window.require is not a function in chrome

### ISSUE THREAD

**Issue by cangshudada** [FE-Mars/monaco-editor-vue#13]
![1586411057(1)](https://user-images.githubusercontent.com/40785860/78861960-bb8d2b80-7a68-11ea-8907-7770d44d6a65.jpg)

**Comment by FE-Mars** [comment]
You can create a demo in CodeSandbox

**Comment by cangshudada** [comment]
sry,I should file an issue with vue-monaco-edito.Thanks.
