### ISSUE TITLE
Syntax Highlighting not working properly [SOLVED]

### ISSUE THREAD

**Issue by dschiller** [FE-Mars/monaco-editor-vue#14]
![image](https://user-images.githubusercontent.com/3144986/78877638-77426100-7a51-11ea-80d5-54ffe9ca2385.png)

![image](https://user-images.githubusercontent.com/3144986/78877672-86c1aa00-7a51-11ea-8362-3e48a2008d4e.png)

**Comment by dschiller** [comment]
Also tried:

```
onEditorMounted(editor, monaco) {
    editor.updateOptions({ "language": "javascript" })  // Doesn't work
    editor.getModel().updateOptions({ "language": "javascript" })  // Doesn't work
    editor.updateOptions({ "lineNumbers": "off" })  // Works
    console.log(editor, monaco)
}
```

**Comment by dschiller** [comment]
Also recognized that there a lot of `#.js` Files which seems to reflect the Syntaxhighlighting Descriptions.

![image](https://user-images.githubusercontent.com/3144986/78888829-bb8a2d00-7a62-11ea-8d0a-6740371b491a.png)

Unfortunetly `javascript` I can not find.

**Comment by dschiller** [comment]
I figured out that 'python'  works.

![image](https://user-images.githubusercontent.com/3144986/78898371-f779be00-7a73-11ea-86f9-15190aefb500.png)

Why does the `JavaScript`Language not work ?

**Comment by FE-Mars** [comment]
documented at https://github.com/Microsoft/monaco-editor-webpack-plugin#options

**Comment by dschiller** [comment]
Thank you a lot! For a Reason I don't know it works now.
