### ISSUE TITLE
Auto Completion doesn't work

### ISSUE THREAD

**Issue by dschiller** [FE-Mars/monaco-editor-vue#17]
Pressing `Ctrl + Space` should show Auto Completion. Doesn't work.

**Comment by FE-Mars** [comment]
Similar problems  [https://github.com/FE-Mars/monaco-editor-vue/issues/25](https://github.com/FE-Mars/monaco-editor-vue/issues/25)

**Comment by dschiller** [comment]
Which Document you mean exactly ? By default that works in the Monaco Playground Examples on the Microsoft Side. Did you disable it by default ?

**Comment by dschiller** [comment]
I added all Features to make sure to not miss anything. But it doesn't work.

![image](https://user-images.githubusercontent.com/3144986/79006725-0fc40880-7b5a-11ea-9e3c-1b765979950e.png)

**Comment by vikyd** [comment]
for JavaScript auto completion in `vue.config.js`:

```js
module.exports = {
  chainWebpack: (config) => {
    config.plugin('monaco-editor').use(MonacoWebpackPlugin, [
      {
        // Languages are loaded on demand at runtime
        languages: ['json', 'javascript', 'html', 'xml'],
        // languages: ['typescript', 'javascript', 'json', 'html', 'xml'],
      },
    ])
  },
}
```

because [monaco-editor-webpack-plugin](https://github.com/microsoft/monaco-editor-webpack-plugin) : 
```
Some languages share the same web worker. If one of the following languages is included, 
you must also include the language responsible for instantiating their shared worker:
```

Language | Instantiator
---|---
javascript | typescript
handlebars | html
scss, less | css
