### ISSUE TITLE
Deselection is not possible

### ISSUE THREAD

**Issue by dschiller** [FE-Mars/monaco-editor-vue#23]
If a Line is selected a Click inside the Selection doesn't set the Cursor and also doesn't clear the Selection.

**Comment by FE-Mars** [comment]
Similar problems  [https://github.com/FE-Mars/monaco-editor-vue/issues/25](https://github.com/FE-Mars/monaco-editor-vue/issues/25)

**Comment by dschiller** [comment]
Which Document you mean exactly ? By default that works in the Monaco Playground Examples on the Microsoft Side. Did you disable it by default ?

**Comment by dschiller** [comment]
I added all Features to make sure to not miss anything. But it doesn't work.

![image](https://user-images.githubusercontent.com/3144986/79006725-0fc40880-7b5a-11ea-9e3c-1b765979950e.png)
