### ISSUE TITLE
Doesn't show Contextmenu

### ISSUE THREAD

**Issue by dschiller** [FE-Mars/monaco-editor-vue#25]
The Monaco Editor has a Contextmenu ( `https://microsoft.github.io/monaco-editor` ). Doesn't work here.

**Comment by FE-Mars** [comment]
Please check the document for Monaco Editor

**Comment by dschiller** [comment]
Which Document you mean exactly ? By default the Contextmenu works in the Monaco Playground Examples on the Microsoft Side. Did you disable it by default ?

**Comment by dschiller** [comment]
I added the `contextmenu` Feature but it doesn't show up.

![image](https://user-images.githubusercontent.com/3144986/79005868-21a4ac00-7b58-11ea-90d1-8a8a621e9881.png)

![image](https://user-images.githubusercontent.com/3144986/79006295-228a0d80-7b59-11ea-89ba-106dd5f8155c.png)

Is there something else I am missing ?
