### ISSUE TITLE
wrong editor size

### ISSUE THREAD

**Issue by cbbrsc** [FE-Mars/monaco-editor-vue#7]
I'm setting the size of the editor but the content is always 5px x 5px

  <MonacoEditor 
                      **width=500
                      height=500**
                      theme="vs-dark"
                      :value="ajson"
                      language="json"
                      :options="options"
                      @editorMounted="onMounted"
                      @change="onChange">
        </MonacoEditor>

![image](https://user-images.githubusercontent.com/10560387/65776426-c75b7500-e14a-11e9-902e-4373d6e20c5a.png)

Any idea?

**Comment by FE-Mars** [comment]
> I'm setting the size of the editor but the content is always 5px x 5px
> 
> <MonacoEditor
> **width=500 height=500**
> theme="vs-dark"
> :value="ajson"
> language="json"
> :options="options"
> @editorMounted="onMounted"
> @change="onChange">
> ![image](https://user-images.githubusercontent.com/10560387/65776426-c75b7500-e14a-11e9-902e-4373d6e20c5a.png)
> 
> Any idea?

Can you create a demo on Codesandbox?

**Comment by iosimliviu** [comment]
Have you found an answer to this issue?

**Comment by FE-Mars** [comment]
> Have you found an answer to this issue?


Ensure that the parent node is in the DOM during initialization
